id: 6e82c8c20aa448b3b799efb45024603e
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_247-Distinguishing_Phenomena_and_What_Is_Meaningful-v1
  language: bo
  author: ''
  volume: {}
